// <auto-generated />
namespace Stack_Undertow.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class qid : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(qid));
        
        string IMigrationMetadata.Id
        {
            get { return "201702171657002_qid"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
